<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.16
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CO'] = array(
	'AMZ' => array(
        "El encanto",
        "La Chorrera",
        "La Pedrera",
        "Leticia",
        "Puerto Alegría",
        "Puerto Arica",
        "Puerto Nariño",
        "Puerto Santander",
        "Tarapacá"
		),
	'ANT' => array(
        "Abejorral",
        "Amagá",
        "Amalfi",
        "Apartadó",
        "Arboletes",
        "Argelia",
        "Barbosa",
        "Bello",
        "Belmira",
        "Caldas",
        "Caramanta",
        "Carepa",
        "Caucasia",
        "Chigorodó",
        "Copacabana",
        "Cáceres",
        "Dabeeiba",
        "Donmatías",
        "El Carmen de Viboral",
        "El peñol",
        "El retiro",
        "Envigado",
        "Frontino",
        "Girardota",
        "Guadalupe",
        "Guarne",
        "Guatapé",
        "Itagüi",
        "Ituango",
        "Jardín",
        "Jericó",
        "La Ceja",
        "La Estrella",
        "La Estrella",
        "La Pintada",
        "Marinilla",
        "Medellín",
        "Nechí",
        "Necolí",
        "Puerto Berrío",
        "Puerto Nare",
        "Puerto triunfo",
        "Rionegro",
        "Sabaneta",
        "San Jerónimo",
        "Santa Fe de Antioquía",
        "Sonsón",
        "Sopetrán",
        "Titiribi",
        "Turbo",
        "Támesis",
        "Urrao",
        "Yarumal"
		),
	'ARU' => array(
        "Arauca",
        "Arauquita",
        "Cravo Norte",
        "Fortul",
        "Puerto Rondón",
        "Saravena",
        "Tame"
		),
	'ATL' => array(
        "Baranoa",
        "Barranquilla",
        "Campeche",
        "Campo de la Cruz",
        "Candelaria",
        "Galapa",
        "Juan de Acosta",
        "Luruaco",
        "Malambo",
        "Mantí",
        "Palmar de Valera",
        "Piojó",
        "Polonuevo",
        "Ponedera",
        "Puerto Colombia",
        "Repelón",
        "Sabanagrande",
        "Sabanalarga",
        "Santa Lucía",
        "Santo Tomás",
        "Soledad",
        "Suan",
        "Tubará",
        "Usiaurí"
		),
	'BOL' => array(
        "Achí",
        "Altos del Rosario",
        "Arenal",
        "Arjona",
        "Arroyohondo",
        "Barranco de Loba",
        "Calamar",
        "Cantagallo",
        "Cartagena",
        "Cicuco",
        "Clemencia",
        "Córdoba",
        "El Carmen de Bolívar",
        "El Guamo",
        "El Peñon",
        "Hatillo de Loba",
        "La Victoria",
        "Magangué",
        "Mahates",
        "Margarita",
        "María la Baja",
        "Montecristo",
        "Morales",
        "Norosí",
        "Pinillos",
        "Regidor",
        "Río Viejo",
        "San Estanislao",
        "San Jacinto",
        "San Jacinto del Cauca",
        "San Juan Nepomuceno",
        "San Martín de Loba",
        "San Pablo",
        "Santa Catalina",
        "Santa Cruz de Mompox",
        "Santa Rosa de Lima",
        "Santa Rosa del Sur",
        "Simití",
        "Soplaviento",
        "Talaigua Nuevo",
        "Tiquisio",
        "Turbaco",
        "Turbaná",
        "Villanueva",
        "Zambrano"
		),
	'BOY' => array(
        "Aquitania",
        "Arcabuco",
        "Belén",
        "Caldas",
        "Chiquinquirá",
        "Chita",
        "Chivatá",
        "Chivor",
        "Chíquiza",
        "Duitama",
        "El Cocuy",
        "Gachantivá",
        "Garagoa",
        "Guateque",
        "Güicán",
        "Iza",
        "Macanal",
        "Miraflores",
        "Monguí",
        "Moniquirá",
        "Muzo",
        "Nobsa",
        "Oicatá",
        "Otanche",
        "Paipa",
        "Paz de río",
        "Pesca",
        "Pisba",
        "Puerto Boyacá",
        "Ramiriquí",
        "Ráquira",
        "Samacá",
        "Santa Rosa de viterbo",
        "Sativanorte",
        "Sativasur",
        "Soatá",
        "Socha",
        "Sogamoso",
        "Soracá",
        "Sotaquirá",
        "Sutamarchán",
        "Sáchica",
        "Tibasosa",
        "Tipacoque",
        "Toca",
        "Tota",
        "Tunja",
        "Turmequé",
        "Tuta",
        "Ventaquemada",
        "Villa de Leyva"
		),
	'CAL' => array(
        "Aguadas",
        "Anserma",
        "Aranzazu",
        "Belalcázar",
        "Chinchiná",
        "Filadelfia",
        "La Dorada",
        "La Merced",
        "Manizales",
        "Manzanares",
        "Marmato",
        "Marquetalia",
        "Marulanda",
        "Neira",
        "Norcasia",
        "Palestina",
        "Pensilvania",
        "Pácora",
        "Riosucio",
        "Risaralda",
        "Salamina",
        "Samaná",
        "San José",
        "Supía",
        "Victoria",
        "Villamaría",
        "Viterbo"
		),
	'CAQ' => array(
        "Albania",
        "Belén de los Andaquíes",
        "Cartagena del Chairá",
        "Curillo",
        "El Doncello",
        "El Paujil",
        "Florencia",
        "La Montañita",
        "Morelia",
        "Puerto Milán",
        "Puerto Rico",
        "San José del Fragua",
        "San Vicente del Caguán",
        "Solano",
        "Solita",
        "Valparaíso"
		),
	'CAS' => array(
        "Aguazul",
        "Chámeza",
        "Hato Corozal",
        "La Salina",
        "Maní",
        "Monterrey",
        "Nunchía",
        "Orocué",
        "Paz de Ariporo",
        "Pore",
        "Recetor",
        "Sabanalarga",
        "Safn Luis de Palenque",
        "Sácama",
        "Tauramena",
        "Trinidad",
        "Támara",
        "Villanueva",
        "Yopal"
		),
	'CAU' => array(
        "Almaguer",
        "Argelia",
        "Balboa",
        "Bolívar",
        "Buenos Aires",
        "Cajibío",
        "Caldono",
        "Caloto",
        "Corinto",
        "El Tambo",
        "Florencia",
        "Guachené",
        "Guapí",
        "Jambaló",
        "La Sierra",
        "La Vega",
        "López de Micay",
        "Mercaderes",
        "Miranda",
        "Morales",
        "Padilla",
        "Patía",
        "Piendamó",
        "Popayán",
        "Puerto Tejada",
        "Puracé-Coconuco",
        "Páez",
        "Rosas",
        "San Sebastián",
        "Santa Rosa",
        "Santander de Quilichao",
        "Silvia",
        "Sotará",
        "Sucre",
        "Suárez",
        "Timbiquí",
        "Tmbío",
        "Toribío",
        "Totoró",
        "Villa Rica",
        "inzá"
		),
	'CES' => array(
        "Aguachica",
        "Agustín Codazzi",
        "Astrea",
        "Atánquez",
        "Becerril",
        "Bosconia",
        "Chimichagua",
        "Chiriguaná",
        "Curumaní",
        "El Copey",
        "El Paso",
        "Gamarra",
        "Gonzaléz",
        "La Gloria",
        "La Jagua de Ibirico",
        "La Paz",
        "Manaure Balcón del Cesar",
        "Pailitas",
        "Patillal",
        "Pelaya",
        "Pueblo Bello",
        "Rio de Oro",
        "San Alberto",
        "San Diego",
        "San Martín",
        "Tamalameque",
        "Valencia de Jesús",
        "Valledupar"
		),
	'CHOC'  => array(
        "Acandí",
        "Alto Baudó",
        "Bagadó",
        "Bahía Solano",
        "Bajo Baudó",
        "Bojayá",
        "Cantón de San Pablo",
        "Condoto",
        "Cértegui",
        "El Carmen de Atrato",
        "Istmina",
        "Juradó",
        "Litoral de San Juan Sipí",
        "Lloró",
        "Medio Atrato",
        "Medio Baudó",
        "Medio San Juan",
        "Nuquí",
        "Nóvita",
        "Quibdó",
        "Riosucio",
        "Río Iró",
        "Río Quito",
        "San José del Palmar",
        "Tadó",
        "Unguia",
        "Unión Panamericana",
        "Vigía del Fuerte"
		),
	'COR' => array(
        "Ayapel",
        "Canalete",
        "Cereté",
        "Chimá",
        "Chinú",
        "Cotorra",
        "La Aparta",
        "Los Córdobas",
        "Momil",
        "Montelíbano",
        "Montería",
        "Moñitos",
        "Planeta Rica",
        "Pueblo Nuevo",
        "Puerto Escondido",
        "Puerto Libertador",
        "Purísima",
        "Sahagún",
        "San Andres de Sotavento",
        "San Antero",
        "San Bernardo del Viento",
        "San Carlos",
        "San José de Uré",
        "San Pelayo",
        "Santa Cruz	de Lorica",
        "Tierralta",
        "Tuchín",
        "Valencia"
		),
	'CUN' => array(
        "Albán",
        "Anapoima",
        "Anolaima",
        "Arbeláez",
        "Bogotá D.C",
        "Bojacá",
        "Cachipay",
        "Cajicá",
        "Choachí",
        "Chocontá",
        "Chía",
        "Cota",
        "Cucunubá",
        "Cáqueza",
        "Facatativá",
        "Funza",
        "Fusagasugá",
        "Fúquene",
        "Gachalá",
        "Gachetá",
        "Girardot",
        "Guaduas",
        "Guatavita",
        "Gutiérrez",
        "La Calera",
        "La Mesa",
        "La Vega",
        "Madrid",
        "Mosquera",
        "Nemocón",
        "Pachco",
        "Pandi",
        "Pasca",
        "Ricaurte",
        "San Bernardo",
        "Sasaima",
        "Sibáté",
        "Simijaca",
        "Soacha",
        "Sopó",
        "Suesca",
        "Sutatausa",
        "Tabio",
        "Tausa",
        "Tena",
        "Tenjo",
        "Tocaima",
        "Tocancipá",
        "Ubaté",
        "Villapinzón",
        "Villeta",
        "Zipacón",
        "Zipaquirá"
		),
	'GUA' => array(
        "Cacahual",
        "Guaviare",
        "Inírida",
        "Morichal Nuevo",
        "Pana Pana",
        "Puerto Colombia",
        "San Felipe"
		),
	'GUV' => array(
        "Calamar",
        "El Retorno",
        "Miraflores",
        "San José del Guaviare"
		),
	'HUI' => array(
        "Acevedo",
        "Agrado",
        "Aipe",
        "Algeciras",
        "Altamira",
        "Baraya",
        "Campoalegre",
        "Colombia",
        "El Pital",
        "Elías",
        "Garzón",
        "Gigante",
        "Guadalupe",
        "Hobo",
        "Isnos",
        "La Argentina",
        "La Plata",
        "Neiva",
        "Nátaga",
        "Oporapa",
        "Palermo",
        "Palestina",
        "Paycol",
        "Pitalito",
        "Rivera",
        "Saladoblanco",
        "San Agustín",
        "Santa María",
        "Suaza",
        "Tarqui",
        "Tello",
        "Teruel",
        "Tesalia",
        "Timaná",
        "Villavieja",
        "Yaguará",
        "Íquira"
		),
	'GUJ' => array(
        "Albania",
        "Barrancas",
        "Dibulla",
        "Distracción",
        "El Molino",
        "Fonseca",
        "Hatonuevo",
        "La Jagua del Pilar",
        "Maicao",
        "Manaure",
        "Riohacha",
        "San Juan del Cesar",
        "Uribia",
        "Urumita",
        "Villanueva"
		),
	'MAG' => array(
        "Algarrobo",
        "Aracataca",
        "Ariguaní",
        "Cerro de San Antonio",
        "Chibolo",
        "Ciénaga",
        "Concordia",
        "El Banco",
        "El Piñon",
        "El Retén",
        "Fundación",
        "Guamal",
        "Nueva Granada",
        "Pedraza",
        "Pijiño del Carmen",
        "Pivijay",
        "Plato",
        "Pueblo Viejo",
        "Remolino",
        "Sabanas de San Angel",
        "San Fernando",
        "San Sebastian de Buenavista",
        "San Zenón",
        "Santa Ana",
        "Santa Bárbara de Pinto",
        "Santa Marta",
        "Sitinuevo",
        "Tenerife",
        "Zapayán",
        "Zona Bananera"
		),
	'MET' => array(
        "Acacías",
        "Barranca de Upía",
        "Cabuyaro",
        "Castilla de la Nueva",
        "Cubarral",
        "Cumaral",
        "El Calvario",
        "El Dorado",
        "El castillo",
        "Fuente de Oro",
        "Granada",
        "Guamal",
        "La Macarena",
        "La Uribe",
        "Lejanias",
        "Mapiripán",
        "Mesetas",
        "Puerto Concordia",
        "Puerto Gaitán",
        "Puerto Lleras",
        "Puerto López",
        "Puerto Rico",
        "Restrepo",
        "San Carlos de Guaroa",
        "San Juan de Arama",
        "San Juanito",
        "San Martín",
        "Villavicencio",
        "Vista Hermosa"
		),
	'NAR' => array(
        "Aldana",
        "Ancuyá",
        "Arboleda",
        "Barbacoas",
        "Buesaco",
        "Chachagüi",
        "Consacá",
        "Contadero",
        "Cuaspud",
        "Cumbal",
        "Cumbitarra",
        "El Charco",
        "El Rosario",
        "El Tablón",
        "El Tambo",
        "Funes",
        "Guachucal",
        "Guaitarilla",
        "Gualmatán",
        "Imués",
        "Ipiales",
        "La Cruz",
        "La Florida",
        "La Llanada",
        "La Tola",
        "La Unión",
        "Leiva",
        "Linares",
        "Magüi Payán",
        "Mallama",
        "Mosquera",
        "Ospina",
        "Pasto",
        "Policarpa",
        "Potosí",
        "Providencia",
        "Puerres",
        "Pupiales",
        "Ricaurte",
        "Roberto Payán",
        "Samaniego",
        "San Pablo",
        "Sandoná",
        "Santa Bárbara",
        "Santacruz",
        "Sapuyes",
        "Taminango",
        "Tangua",
        "Tumaco",
        "Túquerres",
        "Yacuanquer"
		),
	'NOR' => array(
        "Arboledas",
        "Bochalema",
        "Chinácota",
        "Chitagá",
        "Conveción",
        "Cucutilla",
        "Cáchira",
        "Cúcuta",
        "Durania",
        "El Carmen",
        "El Tarra",
        "El Zulia",
        "Gramalote",
        "Hacarí",
        "La playa del Belén",
        "Los Patios",
        "Ocaña",
        "Pamplona",
        "Pamplonita",
        "Puerto Santander",
        "Salazar de las Palmas",
        "San Calixto",
        "Santiago",
        "Sardinata",
        "Teorama",
        "Tibú",
        "Toledo",
        "Villa del Rosario",
        "Ábrego"
		),
	'PUT' => array(
        "Colón",
        "Mocoa",
        "Orito",
        "Puerto Asís",
        "Puerto Caicedo",
        "Puerto Guzmán",
        "Puerto Leguízamo",
        "San Francisco",
        "San Miguel",
        "Santiago",
        "Sibundoy",
        "Valle de Guamuez",
        "Villagarzón"
		),
	'QUI' => array(
        "Armenia",
        "Buenavista",
        "Calarcá",
        "Circasia",
        "Córdoba",
        "Finlandia",
        "Génova",
        "La Tebaida",
        "Montenegro",
        "Pijao",
        "Quimbaya",
        "Salento"
		),
	'RIS' => array(
        "Apía",
        "Balboa",
        "Belén de Umbría",
        "Dosquebradas",
        "Guática",
        "La Celia",
        "La Virginia",
        "Marsella",
        "Mistrató",
        "Pereira",
        "Pueblo Rico",
        "Quinchía",
        "Santa Rosa de Cabal",
        "Santuario"
		),
	'SAP' => array(
			"San Andres"
		),
	'SAN'  => array(
        "Aguada",
        "Albania",
        "Aratoca",
        "Barbosa",
        "Barichara",
        "Barranbermeja",
        "Betulia",
        "Bucaramanga",
        "Capitanejo",
        "Carcasí",
        "Cepitá",
        "Charalá",
        "Chima",
        "Chipatá",
        "Cimitarra",
        "Curití",
        "El Socorro",
        "Encino",
        "Floridablanca",
        "Guaca",
        "Guadalupe",
        "Guapotá",
        "Gámbita",
        "Güepsa",
        "Hato",
        "Lebrija",
        "Los Santos",
        "Matanza",
        "Mogotes",
        "Mologavita",
        "Málaga",
        "Oiba",
        "Onzaga",
        "Pidecuesta",
        "Puente Nacional",
        "Puerto Wilches",
        "Páramo",
        "Rionegro",
        "Sabana de Torres",
        "San Andrés",
        "San Benito",
        "San Gil",
        "San Joaquín",
        "San Juan de Girón",
        "San Vicente de Chucurí",
        "Santa Bárbara",
        "Santa Helena del Opón",
        "Simacota",
        "Valle de San José",
        "Vélez",
        "Zapatoca"
		),
	'SUC' => array(
        "Buenavista",
        "Buenavista",
        "Caimito",
        "Chalán",
        "Colosó",
        "Corozal",
        "Coveñas",
        "El Roble",
        "Guaranda",
        "La Unión",
        "Los Palmitos",
        "Majagual",
        "Morroa",
        "Ovejas",
        "Sampués",
        "San Antonio de Palmito",
        "San Benito Abad",
        "San Juan de Betulia",
        "San Marcos",
        "San Onofre",
        "San Pedro",
        "Sincelejo",
        "Sincé",
        "Sucre",
        "Tolú",
        "Tolú Viejo"
		),
	'TOL' => array(
        "Alpujarra",
        "Alvarado",
        "Ambalema",
        "Anzoátegui",
        "Armero Guayabal",
        "Ataco",
        "Cajamarca",
        "Carmen de Apicalá",
        "Casabianca",
        "Chaparral",
        "Coello",
        "Coyaima",
        "Cunday",
        "Dolores",
        "El espinal",
        "Falán",
        "Flandes",
        "Fresno",
        "Guamo",
        "Herveo",
        "Honda",
        "Ibague",
        "Icononzo",
        "Lérida",
        "Líbano",
        "Mariquita",
        "Melgar",
        "Murillo",
        "Natagaima",
        "Ortega",
        "Palocabildo",
        "Piedras",
        "Planadas",
        "Prado",
        "Purificación",
        "Rioblanco",
        "Roncesvalles",
        "Rovira",
        "Saldaña",
        "San Antonio",
        "San Luis",
        "Santa Isabel",
        "Suárez",
        "Valle de San Juan",
        "Venadillo",
        "Villahermosa",
        "Villarrica"
		),
	'VAC' => array(
        "Alcalá",
        "Andalucía",
        "Ansermanuevo",
        "Argelia",
        "Bolívar",
        "Buenaventura",
        "Buga",
        "Bugalagrande",
        "Caicedonia",
        "Cali",
        "Candelaria",
        "Cartago",
        "Dagua",
        "Darién",
        "El Cairo",
        "El Cerrito",
        "El Dovio",
        "El Águila",
        "Florida",
        "Ginebra",
        "Guacarí",
        "Jamundí",
        "La Cumbre",
        "La Unión",
        "La Victoria",
        "Obando",
        "Palmira",
        "Pradera",
        "Restrepo",
        "Riofrío",
        "Roldanillo",
        "San Pedro",
        "Sevilla",
        "Toro",
        "Trujillo",
        "Tulúa",
        "Ulloa",
        "Versalles",
        "Vijes",
        "Yotoco",
        "Yumbo",
        "Zarzal"
		),
	'VAU' => array(
        "Acaricuara",
        "Carurú",
        "Mitú",
        "Papanaua",
        "Taraira",
        "Yavaraté"
	    ),
	'VIC' => array(
        "Cumaribo",
        "La Primavera",
        "Puerto Carreño",
        "San José de Maipures",
        "San José de Ocune",
        "Santa Rosalía"
		)
	);
