<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.10
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CO'] = array(
	'AMZ' => array(

			"Leticia",
			"Puerto Nariño",
			"La Chorrera",
			"Tarapacá",
			"La Pedrera",
			"Puerto Santander",
			"El encanto",
			"Puerto Arica",
			"Puerto Alegría"
		),
	'ANT' => array(
			"Medellín",
			"Bello",
			"Jardín",
			"Santa Fe de Antioquía",
			"Rionegro",
			"Caucasia",
			"Envigado",
			"Itagüi",
			"Arboletes",
			"La Estrella",
			"Marinilla",
			"Guatapé",
			"Sabaneta",
			"San Jerónimo",
			"La Pintada",
			"Turbo",
			"Guarne",
			"Apartadó",
			"Puerto Berrío",
			"Puerto Nare",
			"Támesis",
			"Sonsón",
			"Yarumal",
			"El retiro",
			"Caramanta",
			"El peñol",
			"Necolí",
			"Belmira",
			"El Carmen de Viboral",
			"Sopetrán",
			"La Ceja",
			"Amalfi",
			"Jericó",
			"Chigorodó",
			"Nechí",
			"Puerto triunfo",
			"Caldas",
			"Dabeeiba",
			"Carepa",
			"Girardota",
			"La Estrella",
			"Argelia",
			"Donmatías",
			"Ituango",
			"Abejorral",
			"Barbosa",
			"Copacabana",
			"Titiribi",
			"Amagá",
			"Frontino",
			"Urrao",
			"Cáceres",
			"Guadalupe"
		),
	'ARU' => array(
			"Arauca",
			"Tame",
			"Saravena",
			"Fortul",
			"Arauquita",
			"Cravo Norte",
			"Puerto Rondón"
		),
	'ATL' => array(
			"Barranquilla",
			"Malambo",
			"Baranoa",
			"Galapa",
			"Soledad",
			"Luruaco",
			"Juan de Acosta",
			"Mantí",
			"Sabanalarga",
			"Puerto Colombia",
			"Campo de la Cruz",
			"Candelaria",
			"Palmar de Valera",
			"Sabanagrande",
			"Tubará",
			"Santa Lucía",
			"Piojó",
			"Usiaurí",
			"Santo Tomás",
			"Polonuevo",
			"Ponedera",
			"Repelón",
			"Suan",
			"Campeche"
		),
	'BOL' => array(
			"Cartagena",
			"Magangué",
			"El Carmen de Bolívar",
			"Santa Cruz de Mompox",
			"San Jacinto",
			"Turbaco",
			"María la Baja",
			"Arjona",
			"San Juan Nepomuceno",
			"Achí",
			"Calamar",
			"Santa Rosa del Sur",
			"Simití",
			"San Pablo",
			"Cantagallo",
			"Soplaviento",
			"Río Viejo",
			"San Martín de Loba",
			"Santa Catalina",
			"Pinillos",
			"Tiquisio",
			"Mahates",
			"Zambrano",
			"Clemencia",
			"Turbaná",
			"Cicuco",
			"San Estanislao",
			"Santa Rosa de Lima",
			"Morales",
			"Arroyohondo",
			"Regidor",
			"Arenal",
			"Altos del Rosario",
			"Barranco de Loba",
			"El Guamo",
			"Montecristo",
			"Hatillo de Loba",
			"Talaigua Nuevo",
			"El Peñon",
			"San Jacinto del Cauca",
			"Margarita",
			"Norosí",
			"Córdoba",
			"Villanueva",
			"La Victoria" 
		),
	'BOY' => array(
			"Tunja",
			"Sogamoso",
			"Duitama",
			"Paipa",
			"Chiquinquirá",
			"El Cocuy",
			"Puerto Boyacá",
			"Moniquirá",
			"Villa de Leyva",
			"Monguí",
			"Nobsa",
			"Ráquira",
			"Tibasosa",
			"Soatá",
			"Garagoa",
			"Samacá",
			"Paz de río",
			"Muzo",
			"Toca",
			"Aquitania",
			"Guateque",
			"Tota",
			"Güicán",
			"Iza",
			"Tuta",
			"Turmequé",
			"Chivor",
			"Ramiriquí",
			"Pesca",
			"Santa Rosa de viterbo",
			"Ventaquemada",
			"Belén",
			"Otanche",
			"Socha",
			"Soracá",
			"Sáchica",
			"Arcabuco",
			"Macanal",
			"Sutamarchán",
			"Chita",
			"Gachantivá",
			"Sativanorte",
			"Sotaquirá",
			"Tipacoque",
			"Miraflores",
			"Chivatá",
			"Oicatá",
			"Pisba",
			"Sativasur",
			"Chíquiza",
			"Caldas"
		),
	'CAL' => array(
			"Manizales",
			"La Dorada",
			"Chinchiná",
			"Risaralda",
			"Aguadas",
			"Anserma",
			"Salamina",
			"Riosucio",
			"Samaná",
			"Pensilvania",
			"Marmato",
			"Manzanares",
			"Villamaría",
			"Belalcázar",
			"Supía",
			"Aranzazu",
			"Neira",
			"Palestina",
			"Marquetalia",
			"Pácora",
			"Marulanda",
			"Viterbo",
			"Filadelfia",
			"La Merced",
			"Norcasia",
			"Victoria",
			"San José"
		),
	'CAQ' => array(
			"Florencia",
			"San Vicente del Caguán",
			"Belén de los Andaquíes",
			"Puerto Rico",
			"La Montañita",
			"El Doncello",
			"El Paujil",
			"Cartagena del Chairá",
			"Curillo",
			"Morelia",
			"Solita",
			"San José del Fragua",
			"Solano",
			"Albania",
			"Valparaíso",
			"Puerto Milán" 
		),
	'CAS' => array(
			"Yopal",
			"Paz de Ariporo",
			"Maní",
			"Orocué",
			"Aguazul",
			"Monterrey",
			"Sabanalarga",
			"Villanueva",
			"Pore",
			"Támara",
			"Hato Corozal",
			"Safn Luis de Palenque",
			"Tauramena",
			"Trinidad",
			"Sácama",
			"La Salina",
			"Nunchía",
			"Recetor",
			"Chámeza"
		),
	'CAU' => array(
			"Popayán",
			"Santander de Quilichao",
			"Guapí",
			"Caloto",
			"Puerto Tejada",
			"Patía",
			"Silvia",
			"Puracé-Coconuco",
			"Timbiquí",
			"Sotará",
			"Páez",
			"inzá",
			"Piendamó",
			"El Tambo",
			"Corinto",
			"La Sierra",
			"Mercaderes",
			"Balboa",
			"Tmbío",
			"Santa Rosa",
			"Miranda",
			"Suárez",
			"Morales",
			"Bolívar",
			"Rosas",
			"Almaguer",
			"Cajibío",
			"Toribío",
			"Caldono",
			"La Vega",
			"Totoró",
			"Argelia",
			"Jambaló",
			"Villa Rica",
			"Sucre",
			"Padilla",
			"López de Micay",
			"Guachené",
			"Buenos Aires",
			"Florencia",
			"San Sebastián"

		),
	'CES' => array(
			"Valledupar",
			"Aguachica",
			"Chiriguaná",
			"Chimichagua",
			"Agustín Codazzi",
			"La Jagua de Ibirico",
			"Bosconia",
			"Curumaní",
			"San Diego",
			"Becerril",
			"El Paso",
			"El Copey",
			"Manaure Balcón del Cesar",
			"Pueblo Bello",
			"Pailitas",
			"La Paz",
			"San Alberto",
			"Gamarra",
			"La Gloria",
			"Tamalameque",
			"Pelaya",
			"Atánquez",
			"Patillal",
			"Rio de Oro",
			"Gonzaléz",
			"Astrea",
			"San Martín",
			"Valencia de Jesús"
		),
	'CHOC'  => array(
			"Quibdó",
			"Bahía Solano",
			"Condoto",
			"Istmina",
			"Acandí",
			"Tadó",
			"Nuquí",
			"Riosucio",
			"Medio Atrato",
			"Río Quito",
			"El Carmen de Atrato",
			"Bojayá",
			"Nóvita",
			"Lloró",
			"Juradó",
			"Unguia",
			"Alto Baudó",
			"Litoral de San Juan Sipí",
			"Bajo Baudó",
			"Cértegui",
			"Bagadó",
			"San José del Palmar",
			"Medio San Juan",
			"Unión Panamericana",
			"Medio Baudó",
			"Cantón de San Pablo",
			"Río Iró",
			"Vigía del Fuerte"	
		),
	'COR' => array(
			"Montería",
			"Santa Cruz	de Lorica",
			"Sahagún",
			"Ayapel",
			"Cereté",
			"Tierralta",
			"Chinú",
			"Planeta Rica",
			"San Antero",
			"San Pelayo",
			"Puerto Escondido",
			"Moñitos",
			"Montelíbano",
			"Momil",
			"San Bernardo del Viento",
			"San Carlos",
			"La Aparta",
			"Cotorra",
			"Puerto Libertador",
			"Tuchín",
			"Valencia",
			"San Andres de Sotavento",
			"Los Córdobas",
			"Chimá",
			"Canalete",
			"Purísima",
			"Pueblo Nuevo",
			"San José de Uré"
		),
	'CUN' => array(
	        "Bogotá D.C",
			"Chía",
			"Zipaquirá",
			"Facatativá",
			"Soacha",
			"Fusagasugá",
			"Girardot",
			"Ubaté",
			"Funza",
			"Madrid",
			"Guaduas",
			"Mosquera",
			"Guatavita",
			"Cajicá",
			"Tocancipá",
			"Nemocón",
			"Cota",
			"Simijaca",
			"Gachalá",
			"La Calera",
			"Villeta",
			"Fúquene",
			"Anapoima",
			"La Mesa",
			"Sibáté",
			"Anolaima",
			"Tenjo",
			"Tocaima",
			"Pachco",
			"Chocontá",
			"Tausa",
			"Suesca",
			"Sopó",
			"Villapinzón",
			"Cucunubá",
			"Zipacón",
			"Sasaima",
			"La Vega",
			"Cáqueza",
			"Pasca",
			"Gachetá",
			"Tabio",
			"Ricaurte",
			"Sutatausa",
			"Arbeláez",
			"San Bernardo",
			"Tena",
			"Bojacá",
			"Cachipay",
			"Pandi",
			"Choachí",
			"Albán",
			"Gutiérrez"
		),
	'GUA' => array(
			"Inírida",
			"San Felipe",
			"Cacahual",
			"Puerto Colombia",
			"Pana Pana",
			"Morichal Nuevo",
			"Guaviare"
		),
	'GUV' => array(
			"San José del Guaviare",
			"Miraflores",
			"Calamar",
			"El Retorno" 
		),
	'HUI' => array(
			"Neiva",
			"San Agustín",
			"La Plata",
			"Pitalito",
			"Garzón",
			"Villavieja",
			"Acevedo",
			"Aipe",
			"Gigante",
			"Suaza",
			"Campoalegre",
			"Nátaga",
			"Altamira",
			"Palermo",
			"La Argentina",
			"Algeciras",
			"Timaná",
			"Yaguará",
			"Hobo",
			"El Pital",
			"Íquira",
			"Isnos",
			"Tello",
			"Tesalia",
			"Baraya",
			"Paycol",
			"Agrado",
			"Oporapa",
			"Saladoblanco",
			"Tarqui",
			"Teruel",
			"Santa María",
			"Palestina",
			"Guadalupe",
			"Colombia",
			"Rivera",
			"Elías"
		),
	'GUJ' => array(
			"Riohacha",
			"Maicao",
			"Barrancas",
			"Manaure",
			"San Juan del Cesar",
			"Dibulla",
			"Villanueva",
			"Uribia",
			"Fonseca",
			"Urumita",
			"Albania",
			"Hatonuevo",
			"El Molino",
			"Distracción",
			"La Jagua del Pilar"
		),
	'MAG' => array(
			"Santa Marta",
			"Ciénaga",
			"Fundación",
			"Plato",
			"El Banco",
			"Aracataca",
			"Sitinuevo",
			"Pivijay",
			"Pueblo Viejo",
			"Santa Ana",
			"Guamal",
			"Zona Bananera",
			"El Retén",
			"Nueva Granada",
			"Ariguaní",
			"Tenerife",
			"Remolino",
			"El Piñon",
			"San Zenón",
			"Chibolo",
			"Algarrobo",
			"Pedraza",
			"Cerro de San Antonio",
			"Concordia",
			"Sabanas de San Angel",
			"Pijiño del Carmen",
			"Zapayán",
			"San Sebastian de Buenavista",
			"Santa Bárbara de Pinto",
			"San Fernando"
		),
	'MET' => array(
			"Villavicencio",
			"Granada",
			"Acacías",
			"Puerto López",
			"La Macarena",
			"Mesetas",
			"Puerto Gaitán",
			"Barranca de Upía",
			"Restrepo",
			"Guamal",
			"Mapiripán",
			"Castilla de la Nueva",
			"Cabuyaro",
			"Cubarral",
			"Fuente de Oro",
			"Cumaral",
			"Lejanias",
			"San Juan de Arama",
			"El castillo",
			"Puerto Concordia",
			"Puerto Lleras",
			"La Uribe",
			"Vista Hermosa",
			"Puerto Rico",
			"San Carlos de Guaroa",
			"San Martín",
			"San Juanito",
			"El Dorado",
			"El Calvario"	 
		),
	'NAR' => array(
			"Pasto",
			"Tumaco",
			"Ipiales",
			"Túquerres",
			"Cumbal",
			"Sandoná",
			"Samaniego",
			"Barbacoas",
			"San Pablo",
			"La Cruz",
			"Consacá",
			"Pupiales",
			"Chachagüi",
			"Policarpa",
			"El Charco",
			"El Tambo",
			"Guaitarilla",
			"Yacuanquer",
			"Buesaco",
			"Taminango",
			"La Florida",
			"Puerres",
			"Leiva",
			"Tangua",
			"El Tablón",
			"Potosí",
			"Guachucal",
			"Mosquera",
			"Linares",
			"Magüi Payán",
			"Gualmatán",
			"Ricaurte",
			"Imués",
			"Roberto Payán",
			"Sapuyes",
			"La Tola",
			"Ancuyá",
			"Aldana",
			"El Rosario",
			"Mallama",
			"Santa Bárbara",
			"La Unión",
			"Cumbitarra",
			"Contadero",
			"Providencia",
			"Cuaspud",
			"Ospina",
			"La Llanada",
			"Funes",
			"Arboleda",
			"Santacruz" 
		),
	'NOR' => array(
			"Cúcuta",
			"Ocaña",
			"Pamplona",
			"Tibú",
			"Conveción",
			"Villa del Rosario",
			"Chinácota",
			"Ábrego",
			"El Tarra",
			"El Carmen",
			"Pamplonita",
			"Sardinata",
			"Los Patios",
			"Chitagá",
			"Bochalema",
			"Gramalote",
			"El Zulia",
			"Puerto Santander",
			"Cáchira",
			"Cucutilla",
			"Durania",
			"La playa del Belén",
			"Salazar de las Palmas",
			"Toledo",
			"Santiago",
			"Teorama",
			"Arboledas",
			"San Calixto",
			"Hacarí"
		),
	'PUT' => array(
			"Mocoa",
			"Puerto Asís",
			"Orito",
			"Sibundoy",
			"Valle de Guamuez",
			"Puerto Leguízamo",
			"Puerto Caicedo",
			"Puerto Guzmán",
			"San Miguel",
			"Villagarzón",
			"Colón",
			"San Francisco",
			"Santiago"
		),
	'QUI' => array(
			"Armenia",
			"Calarcá",
			"Salento",
			"Montenegro",
			"Quimbaya",
			"Circasia",
			"Pijao",
			"Finlandia",
			"Génova",
			"Buenavista",
			"Córdoba",
			"La Tebaida"
		),
	'RIS' => array(
			"Pereira",
			"Santa Rosa de Cabal",
			"Santuario",
			"Belén de Umbría",
			"Marsella",
			"La Virginia",
			"Dosquebradas",
			"Quinchía",
			"Apía",
			"Balboa",
			"Mistrató",
			"Guática",
			"Pueblo Rico",
			"La Celia" 
		),
	'SAP' => array(
			"San Andres"
		),
	'SAN'  => array(
			"Bucaramanga",
			"Barranbermeja",
			"El Socorro",
			"Floridablanca",
			"San Juan de Girón",
			"San Gil",
			"Vélez",
			"Zapatoca",
			"Barichara",
			"Málaga",
			"Pidecuesta",
			"Charalá",
			"Rionegro",
			"Curití",
			"Santa Helena del Opón",
			"Simacota",
			"Los Santos",
			"Barbosa",
			"San Andrés",
			"Capitanejo",
			"Guaca",
			"San Vicente de Chucurí",
			"Lebrija",
			"Oiba",
			"Mogotes",
			"Valle de San José",
			"Aratoca",
			"Puente Nacional",
			"Puerto Wilches",
			"Cimitarra",
			"Gámbita",
			"Carcasí",
			"San Joaquín",
			"Chipatá",
			"Páramo",
			"Chima",
			"Matanza",
			"Sabana de Torres",
			"Guadalupe",
			"Güepsa",
			"Betulia",
			"Cepitá",
			"Santa Bárbara",
			"Onzaga",
			"Albania",
			"Encino",
			"Guapotá",
			"Mologavita",
			"Aguada",
			"San Benito",
			"Hato"
		),
	'SUC' => array(
			"Sincelejo",
			"Tolú",
			"San Onofre",
			"Corozal",
			"Sampués",
			"Tolú Viejo",
			"Sincé",
			"Morroa",
			"San Marcos",
			"Colosó",
			"San Benito Abad",
			"Coveñas",
			"Los Palmitos",
			"Ovejas",
			"Majagual",
			"San Pedro",
			"Guaranda",
			"Caimito",
			"San Antonio de Palmito",
			"La Unión",
			"El Roble",
			"Chalán",
			"Buenavista",
			"San Juan de Betulia",
			"Sucre",
			"Buenavista"
		),
	'TOL' => array(
			"Ibague",
			"El espinal",
			"Honda",
			"Guamo",
			"Melgar",
			"Chaparral",
			"Mariquita",
			"Purificación",
			"Flandes",
			"Natagaima",
			"Líbano",
			"Planadas",
			"Prado",
			"Saldaña",
			"Carmen de Apicalá",
			"Lérida",
			"Ataco",
			"Rovira",
			"Falán",
			"Coyaima",
			"Coello",
			"Cajamarca",
			"Fresno",
			"Armero Guayabal",
			"Cunday",
			"Villarrica",
			"Alpujarra",
			"Herveo",
			"Anzoátegui",
			"Casabianca",
			"San Luis",
			"Venadillo",
			"Ambalema",
			"Icononzo",
			"Piedras",
			"Roncesvalles",
			"Palocabildo",
			"Santa Isabel",
			"Rioblanco",
			"Ortega",
			"San Antonio",
			"Alvarado",
			"Dolores",
			"Suárez",
			"Villahermosa",
			"Murillo",
			"Valle de San Juan"
		),
	'VAC' => array(
			"Cali",
			"Palmira",
			"Buga",
			"Cartago",
			"Tulúa",
			"Buenaventura",
			"Yumbo",
			"Toro",
			"Jamundí",
			"Roldanillo",
			"La Unión",
			"Darién",
			"Florida",
			"Candelaria",
			"El Cerrito",
			"Ginebra",
			"Obando",
			"Yotoco",
			"Zarzal",
			"Bugalagrande",
			"Ansermanuevo",
			"Versalles",
			"La Victoria",
			"Dagua",
			"El Dovio",
			"Andalucía",
			"Vijes",
			"Riofrío",
			"Ulloa",
			"Alcalá",
			"Caicedonia",
			"El Cairo",
			"Argelia",
			"La Cumbre",
			"Pradera",
			"Restrepo",
			"Guacarí",
			"San Pedro",
			"Bolívar",
			"Sevilla",
			"Trujillo",
			"El Águila"
		),
	'VAU' => array(
			"Mitú",
			"Papanaua",
			"Carurú",
			"Taraira",
			"Yavaraté",
			"Acaricuara"
		),
	'VIC' => array(
			"Puerto Carreño",
			"La Primavera",
			"Cumaribo",
			"Santa Rosalía",
			"San José de Maipures",
			"San José de Ocune"
		)
	
	);
